#!/usr/bin/env node
var source = (
  process.argv[2] ?
    require('fs').createReadStream(process.argv[2]) :
    process.stdin )
var buffers = [ ]
source
  .on('data', function(buffer) {
    buffers.push(buffer) })
  .on('end', function() {
    process.stdout.write(
      require('./')(
        Buffer.concat(buffers).toString())) })
